### ISSUE TITLE
Does it support ActionCable?

### ISSUE THREAD

**Issue by mdesantis** [socketry/falcon#10] opened 2018-06-29 16:23 UTC
Hello, I was messing around with Falcon and I tried booting a Rails 5.2.0 application. I noticed that ActionCable websocket doesn't work, is it expected? Isn't Falcon compatible with ActionCable?

**Comment by ioquatix** [comment] 2018-06-29 22:07
Nope, not yet, but if you debug the issue and let me know what's wrong I'd be happy to help get it working :)

**Comment by mdesantis** [comment] 2018-06-30 08:57
If it can help, looking at the error it seems to me the same issue that I reported on iodine web server yersterday: https://github.com/boazsegev/iodine/issues/38

This is the cause reported by the guy who fixed it:

> The exceptions were raised because the status code reported by ActiveCable was negative (-1), which iodine recognized as an abnormal status code, resulting is the connection being disconnected.
>
> I fixed it so negative status codes would be ignored for hijacking and upgrading purposes.

**Comment by ioquatix** [comment] 2018-06-30 08:59
Can you show me what error you are getting?

**Comment by ioquatix** [comment] 2018-06-30 09:00
Falcon completely ignores the status if the connection is hijacked.

**Comment by mdesantis** [comment] 2018-06-30 09:01
Sure, I'll show you the error

**Comment by mdesantis** [comment] 2018-06-30 09:06
The app is a newly created Rails 5.2.0, Ruby 2.5.1. I added falcon as gem and then started the server with the following command:

`bundle exec falcon serve -b tcp://localhost:3000 --threaded` (I tried forked but the error stays the same):

```
> bundle exec falcon serve -b tcp://localhost:3000 --threaded
I, [2018-06-30T11:03:16.997623 #30127]  INFO -- : Falcon taking flight! Binding to #<Async::IO::SharedEndpoint 1 descriptors for #<Async::IO::HostEndpoint ["localhost", 3000, nil, 1]>> [Async::Container::Threaded with concurrency: 8]
I, [2018-06-30T11:03:16.998253 #30127]  INFO -- : Send `kill -USR1 30127` for detailed status :)
I, [2018-06-30T11:03:16.998689 #30127]  INFO -- : Send `kill -USR1 30127` for detailed status :)
I, [2018-06-30T11:03:16.999043 #30127]  INFO -- : Send `kill -USR1 30127` for detailed status :)
I, [2018-06-30T11:03:17.003951 #30127]  INFO -- : Send `kill -USR1 30127` for detailed status :)
I, [2018-06-30T11:03:17.000646 #30127]  INFO -- : Send `kill -USR1 30127` for detailed status :)
I, [2018-06-30T11:03:17.000812 #30127]  INFO -- : Send `kill -USR1 30127` for detailed status :)
I, [2018-06-30T11:03:17.001006 #30127]  INFO -- : Send `kill -USR1 30127` for detailed status :)
I, [2018-06-30T11:03:16.999170 #30127]  INFO -- : Send `kill -USR1 30127` for detailed status :)

E, [2018-06-30T11:03:19.306461 #30127] ERROR -- #<Async::IO::Socket:0x00007fb1800457c0>: undefined method `headers' for nil:NilClass (NoMethodError)
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/content_encoding.rb:47:in `call'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/middleware.rb:53:in `call'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/server.rb:54:in `block in accept'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/protocol/http11.rb:133:in `receive_requests'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/protocol/http1.rb:59:in `receive_requests'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/server.rb:49:in `accept'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.12.2/lib/async/io/socket.rb:62:in `block in accept_each'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.12.2/lib/async/io/socket.rb:95:in `block in accept'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-1.10.0/lib/async/task.rb:74:in `block in initialize'






E, [2018-06-30T11:03:30.204277 #30127] ERROR -- #<Async::IO::Socket:0x00007fb1800467d8>: undefined method `headers' for nil:NilClass (NoMethodError)
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/content_encoding.rb:47:in `call'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/middleware.rb:53:in `call'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/server.rb:54:in `block in accept'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/protocol/http11.rb:133:in `receive_requests'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/protocol/http1.rb:59:in `receive_requests'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-http-0.27.3/lib/async/http/server.rb:49:in `accept'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.12.2/lib/async/io/socket.rb:62:in `block in accept_each'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.12.2/lib/async/io/socket.rb:95:in `block in accept'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/async-1.10.0/lib/async/task.rb:74:in `block in initialize'
#<Thread:0x00007fb198e438f0@/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:75 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	6: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:75:in `block (2 levels) in spawn'
	5: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:86:in `run'
	4: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:86:in `loop'
	3: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:93:in `block in run'
	2: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:31:in `block in attach'
	1: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:31:in `register'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:31:in `initialize': closed stream (IOError)
```

**Comment by mdesantis** [comment] 2018-06-30 09:07
Looking again at the error it doesn't seem to me related at the one I reported on the other web server, don't know why I was sure about that

**Comment by ioquatix** [comment] 2018-06-30 09:14
Ah yep, I think I see what the problem is... I am putting kids to bed but will check it later, it should be an easy fix.

**Comment by ioquatix** [comment] 2018-06-30 09:19
I've made a quick fix in falcon, can you install the version from git (v0.17.2) and try that?

**Comment by mdesantis** [comment] 2018-06-30 09:35
Bad news: I don't get errors anymore but the websocket doesn't work (the browser just says that he can't establish a connection)

It's weird that I don't get errors; starting falcon with --`verbose` option I get only this:

```
D, [2018-06-30T11:34:06.813428 #32241] DEBUG -- #<Falcon::Server:0x00000000053ea3a0>: Incoming connnection from #<Addrinfo: 127.0.0.1:52030 TCP> to #<Async::HTTP::Protocol::HTTP1:0x00007fbaa4144450>
D, [2018-06-30T11:34:06.813976 #32241] DEBUG -- localhost:3000: GET /cable HTTP/1.1 from #<Addrinfo: 127.0.0.1:52030 TCP>
```

**Comment by ioquatix** [comment] 2018-06-30 12:05
That looks normal.

I don't know how ActionCable works.

I will need to look at the documentation for what it expects.

**Comment by ioquatix** [comment] 2018-07-04 01:43
Okay I am digging into this issue.

It turns out that `async-http` didn't implement hijack in a way that was compatible with `actioncable`. I have a test bed set up now and am working through the options to support this correctly.

**Comment by ioquatix** [comment] 2018-07-04 02:04
So, this gets pretty tricky due to rack hijack being very loosely specified.

## Concurrency

ActionCable's `async` adaptor only works within a single process server. Otherwise, two different web socket clients won't communicate. This problem is pretty easily solved by launching falcon with `--concurrency 1` or `--threaded`. It's actually not directly a problem, if you don't care about your clients being able to talk to each other :)

## Encryption

The second problem is more tricky. Falcon supports both `http`/`https` connections. There are several layers of IO and it's not obvious which one `rack.hijack` should return.

The initial problem was that `rack.hijack` was not returning a raw Socket instance, but an `Async::IO::Socket` wrapper, so it was causing problems in the event reactor.

I fixed that by getting the underlying IO object from the wrapper and returning that. However, whether this works in all cases is not clear.

## Lifetime

`Falcon`/`Async::HTTP` have certain expectations of lifetime, and the way hijack is used in `ActionCable` goes outside the expectations. The solution here was to call `dup` on the underlying IO object, so that the original one can be closed as per the normal lifetime, and the hijacked one is managed separately. It's not clear to me if this is the best behaviour, but it's one way of handling it.

I played around with adding `#detatch` to wrapper: https://github.com/socketry/async/blob/wrapper-detatch/lib/async/wrapper.rb#L146-L153

While I think it's a pretty neat solution for this particular case, it adds a lot of complexity to the wrapper interface (every operation can now fail in strange ways if the io was detached).

cc @janko-m @picatz Just FYI.

**Closed** 2018-07-04 04:02 UTC

**Comment by mdesantis** [comment] 2018-07-04 14:33
@ioquatix sorry for didn't help previously, I forgot about doing that try. I'll try the fixed version and report any further bugs I'll possibly find

**Comment by ioquatix** [comment] 2018-12-27 20:37
Yes.
